# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idm_python/idm_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cidm_python/idm_service.proto\"0\n\x08UserList\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x04list\x18\x02 \x03(\x0b\x32\x05.User\"2\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"6\n\x10UserLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"T\n\x11UserCreateRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"*\n\rDeleteRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"X\n\x19UserChangePasswordRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x17\n\x0f\x63urrentPassword\x18\x02 \x01(\t\x12\x13\n\x0bnewPassword\x18\x03 \x01(\t\"J\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0b\n\x03sub\x18\x04 \x01(\t\"!\n\x0eStringResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe1\x02\n\nIDMService\x12\x32\n\nCreateUser\x12\x12.UserCreateRequest\x1a\x0e.TokenResponse\"\x00\x12,\n\x05Login\x12\x11.UserLoginRequest\x1a\x0e.TokenResponse\"\x00\x12*\n\x06Logout\x12\r.TokenRequest\x1a\x0f.StringResponse\"\x00\x12,\n\tAuthorize\x12\r.TokenRequest\x1a\x0e.TokenResponse\"\x00\x12/\n\nDeleteUser\x12\x0e.DeleteRequest\x1a\x0f.StringResponse\"\x00\x12>\n\x0e\x43hangePassword\x12\x1a.UserChangePasswordRequest\x1a\x0e.TokenResponse\"\x00\x12&\n\x08GetUsers\x12\r.TokenRequest\x1a\t.UserList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idm_python.idm_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERLIST']._serialized_start=32
  _globals['_USERLIST']._serialized_end=80
  _globals['_USER']._serialized_start=82
  _globals['_USER']._serialized_end=132
  _globals['_USERLOGINREQUEST']._serialized_start=134
  _globals['_USERLOGINREQUEST']._serialized_end=188
  _globals['_USERCREATEREQUEST']._serialized_start=190
  _globals['_USERCREATEREQUEST']._serialized_end=274
  _globals['_TOKENREQUEST']._serialized_start=276
  _globals['_TOKENREQUEST']._serialized_end=305
  _globals['_DELETEREQUEST']._serialized_start=307
  _globals['_DELETEREQUEST']._serialized_end=349
  _globals['_USERCHANGEPASSWORDREQUEST']._serialized_start=351
  _globals['_USERCHANGEPASSWORDREQUEST']._serialized_end=439
  _globals['_TOKENRESPONSE']._serialized_start=441
  _globals['_TOKENRESPONSE']._serialized_end=515
  _globals['_STRINGRESPONSE']._serialized_start=517
  _globals['_STRINGRESPONSE']._serialized_end=550
  _globals['_IDMSERVICE']._serialized_start=553
  _globals['_IDMSERVICE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
